version: "3.0"
services:
  # System
  portainer:
    container_name: portainer
    image: portainer/portainer:1.24.1-alpine #last version: portainer/portainer:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    networks:
      - iot_network
    environment:
      - TZ=Europe/Moscow

  volumes_sftp: #read-only all volumes
    container_name: volumes_sftp
    image: atmoz/sftp
    volumes:
      - influxdb_data_volume:/home/user/influxdb_data_volume
      - influxdb_config_volume:/home/user/influxdb_config_volume
      - mosquitto_data_volume:/home/user/mosquitto_data_volume
      - mosquitto_config_volume:/home/user/mosquitto_config_volume
      - nodered_volume:/home/user/nodered_volume
      - zigbee2mqtt_volume:/home/user/zigbee2mqtt_volume
      - homeassistant_volume:/home/user/homeassistant_volume
    ports:
        - "2222:22"
    command: user:pass:1001
    networks:
      - iot_network
    environment:
      - TZ=Europe/Moscow
  #Tools
  chronograf:
    container_name: chronograf
    image: chronograf:1.8.8-alpine #last version: chronograf:latest
    restart: always
    volumes:
      - chronograf_volume:/var/lib/chronograf
    ports:
      - 8888:8888
    networks:
      - iot_network
    depends_on:
      - influxdb
    environment:
      - TZ=Europe/Moscow

  zigbee2mqttAssistant:
    image: carldebilly/zigbee2mqttassistant:0.3.178-linux-x64 #last version: carldebilly/zigbee2mqttassistant:linux-arm64
    container_name: zigbee2mqttAssistant
    env_file:
      - zigbee2mqttAssistant.env
    ports:
      - 8880:8880
    restart: always
    depends_on:
      - eclipse-mosquitto
    networks:
      - iot_network

  #IoT Services
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:0.117.6 #last version: homeassistant/home-assistant:latest
    volumes:
      - homeassistant_volume:/config/
    ports:
      - "8123:8123"
    restart: always
    networks:
      - iot_network
    environment:
      - TZ=Europe/Moscow

  influxdb:
    container_name: influxdb
    image: influxdb:1.8.3-alpine #last version: influxdb:latest
    restart: always
    volumes:
      - influxdb_data_volume:/var/lib/influxdb
      - influxdb_config_volume:/etc/influxdb
    expose:
      - 8086 
      - 8082 
      - 8089
    networks:
      iot_network:
        aliases:
          - influxdb
    environment:
      - TZ=Europe/Moscow

  eclipse-mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12 #last version: eclipse-mosquitto:latest
    restart: always
    volumes:
      - mosquitto_data_volume:/mosquitto/config
      - mosquitto_config_volume:/mosquitto/data
    ports:
      - 1883:1883
    user: '1000:1000'
    networks:
      iot_network:
        aliases:
          - mosquitto
    environment:
      - TZ=Europe/Moscow

  node-red:
    container_name: nodered
    image: nodered/node-red:1.2.3-12-minimal-amd64 #last version: nodered/node-red:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      iot_network:
        aliases:
          - nodered
    volumes:
      - nodered_volume:/data
    # devices: 
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Moscow

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.16.1 #last version: koenkk/zigbee2mqtt:latest
    volumes:
      - zigbee2mqtt_volume:/app/data
      - /run/udev:/run/udev:ro #  is optional, only required for autodetecting the port
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    networks:
      iot_network:
        aliases:
          - zigbee2mqtt
    privileged: true
    depends_on:
      - eclipse-mosquitto
    environment:
      - TZ=Europe/Moscow

volumes:
  # System
  portainer_volume:
  # Tools
  chronograf_volume:
  # IoT Services  
  influxdb_data_volume:
  influxdb_config_volume:
  mosquitto_data_volume:
  mosquitto_config_volume:
  nodered_volume:
  zigbee2mqtt_volume:
  homeassistant_volume:

networks:
  iot_network:
    driver: bridge