version: "3.0"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.23.0
    container_name: filebrowser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./data/filebrowser:/data
      - ./data:/data/share/
    networks:
      - iot_network
    environment:
      - TZ=Europe/Moscow
    command:  ["--root=/data/share", "--address=0.0.0.0", "--database=/data/filebrowser.db", "--config=/data/config.json"]
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.12
    volumes:
      - ./data/homeassistant:/config/
    ports:
      - "8123:8123"
      - "8300:8300"
    restart: always
    networks:
      iot_network:
        aliases:
          - homeassistant
    environment:
      - TZ=Europe/Moscow

  eclipse-mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883
    networks:
      iot_network:
        aliases:
          - mqtt
    environment:
      - TZ=Europe/Moscow

  node-red:
    container_name: nodered
    image: nodered/node-red:3.0.2
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      iot_network:
        aliases:
          - nodered
    user: root
    volumes:
      - ./data/nodered:/data
    privileged: true
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.34.0
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro #  is optional, only required for autodetecting the port
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    ports:
      - "8080:8080"
    networks:
      iot_network:
        aliases:
          - zigbee2mqtt
    privileged: true
    depends_on:
      - eclipse-mosquitto
    environment:
      - TZ=Europe/Moscow

  esphome:
    container_name: esphome
    image: esphome/esphome:2023.2.4
    volumes:
      - ./data/esphome:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6052:6052"
    network_mode: host
    restart: always

networks:
  iot_network:
    driver: bridge
