esphome:
  name: led-tube
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 10dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Tube Fallback Hotspot"
    password: !secret ap_password


light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO0
    num_leds: 8
    name: "NeoPixel Tube"
    effects:
      - addressable_lambda:
          name: "My Custom Effect"
          update_interval: 1000ms
          lambda: |-
            // it.size() - Number of LEDs
            // it[num] - Access the LED at index num.
            // Set the LED at num to the given r, g, b values
            // it[num] = Color(r, g, b);
            // Get the color at index num (Color instance)
            // it[num].get();
            // Example: Simple color wipe
            for (int i = it.size() - 1; i > 0; i--) {
              it[i] = it[i - 1].get();
            }
            it[0] = Color::random_color();
            // Bonus: use .range() and .all() to set many LEDs without having to write a loop.
            //it.range(0, 50) = Color::BLACK;
            //it.all().fade_to_black(10);
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s


#output_power 